# -*- coding: utf-8 -*-
"""LAB-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQzW2sKBrQL82FlaTQCdLvsfElxtQVhx
"""

# dataset

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
N = 3000
x1 = np.random.uniform(-2, 2, N)
x2 = np.random.uniform(-2, 2, N)
X = np.vstack((x1, x2)).T
y = (x1**2 + x2**2 > 1.5).astype(int).reshape(-1,1)

indices = np.random.permutation(N)
train_end = int(0.7 * N)
val_end = int(0.85 * N)
train_idx = indices[:train_end]
val_idx = indices[train_end:val_end]
test_idx = indices[val_end:]

X_train_num, y_train_num = X[train_idx], y[train_idx]
X_val_num, y_val_num = X[val_idx], y[val_idx]
X_test_num, y_test_num = X[test_idx], y[test_idx]

# task 1a

def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def dsigmoid(a):
    return a * (1 - a)
def relu(z):
    return np.maximum(0, z)
def drelu(z):
    return (z > 0).astype(float)

def bce_loss(y, y_hat):
    eps = 1e-8
    y_hat = np.clip(y_hat, eps, 1-eps)
    return -np.mean(y*np.log(y_hat) + (1-y)*np.log(1-y_hat))
def accuracy(y, y_hat):
    return np.mean((y_hat >= 0.5) == y)

class DenseNetwork:
    def __init__(self, layer_sizes, activation='sigmoid'):
        self.L = len(layer_sizes) - 1
        self.activation_type = activation
        self.W = {}
        self.b = {}
        for l in range(1, self.L+1):
            self.W[l] = np.random.randn(layer_sizes[l-1], layer_sizes[l]) * 0.1
            self.b[l] = np.zeros((1, layer_sizes[l]))

    def forward(self, X):
        self.A = {0: X}
        self.Z = {}
        for l in range(1, self.L+1):
            self.Z[l] = self.A[l-1] @ self.W[l] + self.b[l]
            if l == self.L:
                self.A[l] = sigmoid(self.Z[l])
            else:
                if self.activation_type == 'sigmoid':
                    self.A[l] = sigmoid(self.Z[l])
                else:
                    self.A[l] = relu(self.Z[l])
        return self.A[self.L]

    def backward(self, y):
        m = y.shape[0]
        self.dW = {}
        self.db = {}
        dA = self.A[self.L] - y
        for l in reversed(range(1, self.L+1)):
            if l == self.L:
                dZ = dA
            else:
                if self.activation_type == 'sigmoid':
                    dZ = dA * dsigmoid(self.A[l])
                else:
                    dZ = dA * drelu(self.Z[l])
            self.dW[l] = self.A[l-1].T @ dZ / m
            self.db[l] = np.sum(dZ, axis=0, keepdims=True) / m
            dA = dZ @ self.W[l].T

#2
model_2 = DenseNetwork([2, 8, 1], activation='sigmoid')
#5
model_5 = DenseNetwork([2, 8, 8, 8, 8, 1], activation='sigmoid')
#10
model_10 = DenseNetwork([2] + [8]*9 + [1], activation='sigmoid')

# task 1c

class SGD:
    def __init__(self, lr):
        self.lr = lr
    def step(self, model):
        for l in range(1, model.L+1):
            model.W[l] -= self.lr * model.dW[l]
            model.b[l] -= self.lr * model.db[l]

class Momentum:
    def __init__(self, lr, beta=0.9):
        self.lr = lr
        self.beta = beta
        self.vW = {}
        self.vb = {}
    def step(self, model):
        for l in range(1, model.L+1):
            if l not in self.vW:
                self.vW[l] = np.zeros_like(model.W[l])
                self.vb[l] = np.zeros_like(model.b[l])
            self.vW[l] = self.beta*self.vW[l] + self.lr*model.dW[l]
            self.vb[l] = self.beta*self.vb[l] + self.lr*model.db[l]
            model.W[l] -= self.vW[l]
            model.b[l] -= self.vb[l]

def train(model, optimizer, epochs=200):
    train_loss, val_loss = [], []
    train_acc, val_acc = [], []

    for epoch in range(epochs):
        y_hat = model.forward(X_train_num)
        loss = bce_loss(y_train_num, y_hat)
        model.backward(y_train_num)
        optimizer.step(model)
        val_pred = model.forward(X_val_num)
        train_loss.append(loss)
        val_loss.append(bce_loss(y_val_num, val_pred))
        train_acc.append(accuracy(y_train_num, y_hat))
        val_acc.append(accuracy(y_val_num, val_pred))
    return train_loss, val_loss, train_acc, val_acc

# requitred plotting (12 models)

depth_configs = {
    "2-layer":[2,8,1],
    "5-layer":[2,8,8,8,8,1],
    "10-layer":[2]+[8]*9+[1]
}
activations = ["sigmoid","relu"]
optimizers = ["SGD","Momentum"]
results = []

for depth_name, layers in depth_configs.items():
    for act in activations:
        for opt in optimizers:
            print("Training:", depth_name, act, opt)
            model = DenseNetwork(layers, activation=act)
            if opt=="SGD":
                optimizer = SGD(lr=0.1)
            else:
                optimizer = Momentum(lr=0.1, beta=0.9)
            train_loss, val_loss, train_acc, val_acc = train(model, optimizer)

            plt.figure()
            plt.plot(train_loss,label="Train Loss")
            plt.plot(val_loss,label="Val Loss")
            plt.title(f"{depth_name}-{act}-{opt}")
            plt.legend()
            plt.show()

            plt.figure()
            plt.plot(train_acc,label="Train Acc")
            plt.plot(val_acc,label="Val Acc")
            plt.title(f"{depth_name}-{act}-{opt}")
            plt.legend()
            plt.show()

            train_pred = model.forward(X_train_num)
            val_pred = model.forward(X_val_num)
            test_pred = model.forward(X_test_num)
            results.append([
                depth_name,
                act,
                opt,
                accuracy(y_train_num,train_pred),
                accuracy(y_val_num,val_pred),
                accuracy(y_test_num,test_pred),
                bce_loss(y_train_num,train_pred),
                bce_loss(y_val_num,val_pred),
                bce_loss(y_test_num,test_pred)
            ])
for r in results:
  depth_name = r[0]
  activation = r[1]
  optimizer  = r[2]
  train_acc  = r[3]
  val_acc    = r[4]
  test_acc   = r[5]
  train_loss = r[6]
  val_loss   = r[7]
  test_loss  = r[8]
  print(f"\nModel: {depth_name} | Activation: {activation} | Optimizer: {optimizer}")
  print("-"*70)
  print("Final Training Accuracy   :", round(train_acc,4))
  print("Final Validation Accuracy :", round(val_acc,4))
  print("Final Test Accuracy       :", round(test_acc,4))
  print("Final Training Loss       :", round(train_loss,4))
  print("Final Validation Loss     :", round(val_loss,4))
  print("Final Test Loss           :", round(test_loss,4))

# add-on (2 vs 10)

def frobenius_norm(matrix):
    return np.sqrt(np.sum(matrix**2))

def train_with_grad_tracking(model, optimizer, epochs=200):
    first_layer_norm = []
    last_layer_norm = []

    for epoch in range(epochs):
        y_hat = model.forward(X_train)
        model.backward(y_train)
        first_layer_norm.append(frobenius_norm(model.dW[1]))
        last_layer_norm.append(frobenius_norm(model.dW[model.L]))
        optimizer.step(model)

    return first_layer_norm, last_layer_norm

model_2 = DenseNetwork([2,8,1], activation='sigmoid')
optimizer_2 = SGD(lr=0.01)
grad2_first, grad2_last = train_with_grad_tracking(model_2, optimizer_2)

model_10 = DenseNetwork([2]+[8]*9+[1], activation='sigmoid')
optimizer_10 = SGD(lr=0.01)
grad10_first, grad10_last = train_with_grad_tracking(model_10, optimizer_10)

plt.figure()
plt.plot(grad2_first, label="First Layer")
plt.plot(grad2_last, label="Last Layer")
plt.yscale("log")
plt.title("2-Layer Sigmoid: Frobenius Norm of Gradients")
plt.xlabel("Epoch")
plt.ylabel("||∇W||_F (log scale)")
plt.legend()
plt.show()

plt.figure()
plt.plot(grad10_first, label="First Layer")
plt.plot(grad10_last, label="Last Layer")
plt.yscale("log")
plt.title("10-Layer Sigmoid: Frobenius Norm of Gradients")
plt.xlabel("Epoch")
plt.ylabel("||∇W||_F (log scale)")
plt.legend()
plt.show()

plt.figure()
plt.plot(grad2_first, label="2-Layer First")
plt.plot(grad10_first, label="10-Layer First")
plt.yscale("log")
plt.title("First Layer Gradient Comparison")
plt.xlabel("Epoch")
plt.ylabel("||∇W||_F (log scale)")
plt.legend()
plt.show()

# PART 2

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
N = 3000
sigma = 0.1
img_size = 8
def vertical_line():
    img = np.zeros((img_size, img_size))
    img[:, img_size//2] = 1
    return img

def horizontal_line():
    img = np.zeros((img_size, img_size))
    img[img_size//2, :] = 1
    return img

X = []
y = []
for i in range(N):
    if i < N//2:
        img = vertical_line()
        label = 0
    else:
        img = horizontal_line()
        label = 1
    noise = np.random.normal(0, sigma, (img_size, img_size))
    img = img + noise
    X.append(img)
    y.append(label)

X = np.array(X)
y = np.array(y).reshape(-1,1)
print("Dataset shape:", X.shape)
print("Labels shape:", y.shape)

indices = np.random.permutation(N)
train_end = int(0.7*N)
val_end = int(0.85*N)
train_idx = indices[:train_end]
val_idx = indices[train_end:val_end]
test_idx = indices[val_end:]
X_train = X[train_idx]
y_train = y[train_idx]
X_val = X[val_idx]
y_val = y[val_idx]
X_test = X[test_idx]
y_test = y[test_idx]

print("Train:", X_train.shape)
print("Val:", X_val.shape)
print("Test:", X_test.shape)

# task 2a
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_val_flat   = X_val.reshape(X_val.shape[0], -1)
X_test_flat  = X_test.reshape(X_test.shape[0], -1)
print("Flattened shape:", X_train_flat.shape)

def sigmoid(z):
    return 1/(1+np.exp(-z))
def dsigmoid(a):
    return a*(1-a)
def relu(z):
    return np.maximum(0,z)
def drelu(z):
    return (z>0).astype(float)
def bce_loss(y, y_hat):
    eps = 1e-8
    y_hat = np.clip(y_hat, eps, 1-eps)
    return -np.mean(y*np.log(y_hat) + (1-y)*np.log(1-y_hat))
def accuracy(y, y_hat):
    return np.mean((y_hat>=0.5)==y)

class DenseBaseline:
    def __init__(self):
        self.W1 = np.random.randn(64,32) * 0.01
        self.b1 = np.zeros((1,32))
        self.W2 = np.random.randn(32,1) * 0.01
        self.b2 = np.zeros((1,1))

    def forward(self,X):
        self.Z1 = X @ self.W1 + self.b1
        self.A1 = relu(self.Z1)
        self.Z2 = self.A1 @ self.W2 + self.b2
        self.A2 = sigmoid(self.Z2)
        return self.A2

    def backward(self,X,y):
        m = y.shape[0]
        dZ2 = self.A2 - y
        self.dW2 = self.A1.T @ dZ2 / m
        self.db2 = np.sum(dZ2,axis=0,keepdims=True)/m
        dA1 = dZ2 @ self.W2.T
        dZ1 = dA1 * drelu(self.Z1)
        self.dW1 = X.T @ dZ1 / m
        self.db1 = np.sum(dZ1,axis=0,keepdims=True)/m

class SGD:
    def __init__(self,lr=0.1):
        self.lr = lr
    def step(self,model):
        model.W1 -= self.lr * model.dW1
        model.b1 -= self.lr * model.db1
        model.W2 -= self.lr * model.dW2
        model.b2 -= self.lr * model.db2

def train_dense(model, optimizer, epochs=100):
    train_loss_hist, val_loss_hist = [], []
    train_acc_hist, val_acc_hist = [], []
    for epoch in range(epochs):
        y_hat = model.forward(X_train_flat)
        loss = bce_loss(y_train, y_hat)
        model.backward(X_train_flat, y_train)
        optimizer.step(model)
        val_pred = model.forward(X_val_flat)
        train_loss_hist.append(loss)
        val_loss_hist.append(bce_loss(y_val,val_pred))
        train_acc_hist.append(accuracy(y_train,y_hat))
        val_acc_hist.append(accuracy(y_val,val_pred))
    return train_loss_hist, val_loss_hist, train_acc_hist, val_acc_hist

model_dense = DenseBaseline()
optimizer = SGD(lr=0.1)
train_loss, val_loss, train_acc, val_acc = train_dense(model_dense, optimizer, epochs=150)

train_pred = model_dense.forward(X_train_flat)
val_pred   = model_dense.forward(X_val_flat)
test_pred  = model_dense.forward(X_test_flat)

print("Train Accuracy:", accuracy(y_train,train_pred))
print("Validation Accuracy:", accuracy(y_val,val_pred))
print("Test Accuracy:", accuracy(y_test,test_pred))
print("Train Loss:", bce_loss(y_train,train_pred))
print("Validation Loss:", bce_loss(y_val,val_pred))
print("Test Loss:", bce_loss(y_test,test_pred))

# task 2b
class ConvLayer:
    def __init__(self, filter_size=3):
        self.F = filter_size
        self.K = np.random.randn(self.F, self.F) * 0.01
        self.b = 0.0
    def forward(self, X):
        self.X = X
        H, W = X.shape
        out_dim = H - self.F + 1
        self.Z = np.zeros((out_dim, out_dim))
        for i in range(out_dim):
            for j in range(out_dim):
                region = X[i:i+self.F, j:j+self.F]
                self.Z[i,j] = np.sum(region * self.K) + self.b
        return self.Z

    def backward(self, dZ):
        H, W = self.X.shape
        out_dim = H - self.F + 1
        self.dK = np.zeros_like(self.K)
        self.db = 0.0
        dX = np.zeros_like(self.X)
        for i in range(out_dim):
            for j in range(out_dim):
                region = self.X[i:i+self.F, j:j+self.F]
                self.dK += region * dZ[i,j]
                dX[i:i+self.F, j:j+self.F] += self.K * dZ[i,j]
                self.db += dZ[i,j]
        return dX

class ReLU:
    def forward(self, X):
        self.X = X
        return np.maximum(0, X)
    def backward(self, dA):
        return dA * (self.X > 0)

class MaxPool:
    def __init__(self, size=2):
        self.size = size
    def forward(self, X):
        self.X = X
        H, W = X.shape
        out_dim = H // self.size
        self.Z = np.zeros((out_dim, out_dim))
        self.max_mask = np.zeros_like(X)
        for i in range(out_dim):
            for j in range(out_dim):
                region = X[i*self.size:(i+1)*self.size,
                           j*self.size:(j+1)*self.size]
                max_val = np.max(region)
                self.Z[i,j] = max_val
                for m in range(self.size):
                    for n in range(self.size):
                        if region[m,n] == max_val:
                            self.max_mask[i*self.size+m,
                                          j*self.size+n] = 1
        return self.Z

    def backward(self, dZ):
        H, W = self.X.shape
        dX = np.zeros_like(self.X)
        out_dim = dZ.shape[0]
        for i in range(out_dim):
            for j in range(out_dim):
                for m in range(self.size):
                    for n in range(self.size):
                        if self.max_mask[i*self.size+m,
                                         j*self.size+n] == 1:
                            dX[i*self.size+m,
                               j*self.size+n] = dZ[i,j]
        return dX

class Flatten:
    def forward(self, X):
        self.shape = X.shape
        return X.reshape(1,-1)
    def backward(self, dA):
        return dA.reshape(self.shape)

class DenseOutput:
    def __init__(self, input_size):
        self.W = np.random.randn(input_size,1) * 0.01
        self.b = np.zeros((1,1))
    def forward(self, X):
        self.X = X
        self.Z = X @ self.W + self.b
        self.A = 1/(1+np.exp(-self.Z))
        return self.A
    def backward(self, y):
        m = y.shape[0]
        dZ = self.A - y
        self.dW = self.X.T @ dZ
        self.db = dZ
        dX = dZ @ self.W.T
        return dX

class SimpleCNN:
    def __init__(self):
        self.conv = ConvLayer(3)
        self.relu = ReLU()
        self.pool = MaxPool(2)
        self.flatten = Flatten()
        self.fc = DenseOutput(9)
    def forward(self, X):
        z = self.conv.forward(X)
        a = self.relu.forward(z)
        p = self.pool.forward(a)
        f = self.flatten.forward(p)
        out = self.fc.forward(f)
        return out
    def backward(self, y):
        d_fc = self.fc.backward(y)
        d_flat = self.flatten.backward(d_fc)
        d_pool = self.pool.backward(d_flat)
        d_relu = self.relu.backward(d_pool)
        d_conv = self.conv.backward(d_relu)

def train_cnn(model, X_train, y_train, epochs=5, lr=0.01):
    for epoch in range(epochs):
        total_loss = 0
        for i in range(len(X_train)):
            X_sample = X_train[i]
            y_sample = y_train[i].reshape(1,1)
            y_hat = model.forward(X_sample)
            loss = - (y_sample*np.log(y_hat+1e-8) +
                     (1-y_sample)*np.log(1-y_hat+1e-8))
            total_loss += loss
            model.backward(y_sample)
            model.conv.K -= lr * model.conv.dK
            model.conv.b -= lr * model.conv.db
            model.fc.W -= lr * model.fc.dW
            model.fc.b -= lr * model.fc.db
        print("Epoch:", epoch, "Loss:", total_loss/len(X_train))

cnn = SimpleCNN()
train_cnn(cnn, X_train, y_train, epochs=5, lr=0.01)

# task 2c
dense_params = 0
for l in range(1, model.L + 1):
    dense_params += model.W[l].size
    dense_params += model.b[l].size
print("Dense Parameters:", dense_params)

cnn_params = (
    cnn.conv.K.size + 1 +
    cnn.fc.W.size + cnn.fc.b.size
)
print("CNN Parameters:", cnn_params)

print("\nParameter Comparison:")
print("Dense Model:", dense_params)
print("CNN Model:", cnn_params)
print("Dense / CNN ratio:", dense_params / cnn_params)

# task 2d
class Dropout:
    def __init__(self, p=0.5):
        self.p = p
    def forward(self, X, training=True):
        if training:
            self.mask = (np.random.rand(*X.shape) > self.p).astype(float)
            return X * self.mask
        else:
            return X * (1 - self.p)
    def backward(self, dA):
        return dA * self.mask

class CNN_NoPool:
    def __init__(self):
        self.conv = ConvLayer(3)
        self.relu = ReLU()
        self.flatten = Flatten()
        self.fc = DenseOutput(36)
    def forward(self, X):
        z = self.conv.forward(X)
        a = self.relu.forward(z)
        f = self.flatten.forward(a)
        out = self.fc.forward(f)
        return out
    def backward(self, y):
        d_fc = self.fc.backward(y)
        d_flat = self.flatten.backward(d_fc)
        d_relu = self.relu.backward(d_flat)
        self.conv.backward(d_relu)

class CNN_WithDropout:
    def __init__(self, p=0.5):
        self.conv = ConvLayer(3)
        self.relu = ReLU()
        self.dropout = Dropout(p)
        self.pool = MaxPool(2)
        self.flatten = Flatten()
        self.fc = DenseOutput(9)
    def forward(self, X, training=True):
        z = self.conv.forward(X)
        a = self.relu.forward(z)
        d = self.dropout.forward(a, training)
        p = self.pool.forward(d)
        f = self.flatten.forward(p)
        out = self.fc.forward(f)
        return out
    def backward(self, y):
        d_fc = self.fc.backward(y)
        d_flat = self.flatten.backward(d_fc)
        d_pool = self.pool.backward(d_flat)
        d_drop = self.dropout.backward(d_pool)
        d_relu = self.relu.backward(d_drop)
        self.conv.backward(d_relu)

def train_and_evaluate(model, epochs=5, lr=0.01):

    train_loss_hist = []
    val_loss_hist   = []
    train_acc_hist  = []
    val_acc_hist    = []

    for epoch in range(epochs):

        total_loss = 0
        correct = 0

        for i in range(len(X_train)):
            X_sample = X_train[i]
            y_sample = y_train[i].reshape(1,1)

            if hasattr(model, "dropout"):
                y_hat = model.forward(X_sample, training=True)
            else:
                y_hat = model.forward(X_sample)

            loss = - (y_sample*np.log(y_hat+1e-8) +
                     (1-y_sample)*np.log(1-y_hat+1e-8))

            total_loss += loss.item()

            if (y_hat >= 0.5) == y_sample:
                correct += 1

            model.backward(y_sample)

            model.conv.K -= lr * model.conv.dK
            model.conv.b -= lr * model.conv.db
            model.fc.W   -= lr * model.fc.dW
            model.fc.b   -= lr * model.fc.db

        train_loss = total_loss / len(X_train)
        train_acc  = correct / len(X_train)

        val_correct = 0
        val_loss_total = 0

        for i in range(len(X_val)):
            if hasattr(model, "dropout"):
                y_hat = model.forward(X_val[i], training=False)
            else:
                y_hat = model.forward(X_val[i])

            loss = - (y_val[i]*np.log(y_hat+1e-8) +
                     (1-y_val[i])*np.log(1-y_hat+1e-8))

            val_loss_total += loss.item()

            if (y_hat >= 0.5) == y_val[i]:
                val_correct += 1

        val_loss = val_loss_total / len(X_val)
        val_acc  = val_correct / len(X_val)

        train_loss_hist.append(train_loss)
        val_loss_hist.append(val_loss)
        train_acc_hist.append(train_acc)
        val_acc_hist.append(val_acc)

    plt.figure()
    plt.plot(train_loss_hist, label="Train Loss")
    plt.plot(val_loss_hist, label="Val Loss")
    plt.title("Loss vs Epoch")
    plt.legend()
    plt.show()

    plt.figure()
    plt.plot(train_acc_hist, label="Train Acc")
    plt.plot(val_acc_hist, label="Val Acc")
    plt.title("Accuracy vs Epoch")
    plt.legend()
    plt.show()

    test_correct = 0
    test_loss_total = 0

    for i in range(len(X_test)):
        if hasattr(model, "dropout"):
            y_hat = model.forward(X_test[i], training=False)
        else:
            y_hat = model.forward(X_test[i])

        loss = - (y_test[i]*np.log(y_hat+1e-8) +
                 (1-y_test[i])*np.log(1-y_hat+1e-8))

        test_loss_total += loss.item()

        if (y_hat >= 0.5) == y_test[i]:
            test_correct += 1

    test_acc = test_correct / len(X_test)
    test_loss = test_loss_total / len(X_test)

    print("Final Test Accuracy:", round(test_acc,4))
    print("Final Test Loss:", round(test_loss,4))

    return train_acc, val_acc, test_acc, train_loss, val_loss, test_loss

# cnn with pooling
cnn_pool = SimpleCNN()
res_pool = train_and_evaluate(cnn_pool)
# cnn without pooling
cnn_nopool = CNN_NoPool()
res_nopool = train_and_evaluate(cnn_nopool)
# cnn with dropout
cnn_dropout = CNN_WithDropout(p=0.5)
res_dropout = train_and_evaluate(cnn_dropout)
# cnn without dropout
cnn_nodrop = SimpleCNN()
res_nodrop = train_and_evaluate(cnn_nodrop)

print("Train Accuracy, Validation Accuracy, Test Accuracy, Train Loss, Validation Loss, Test Loss")
print("\nCNN with Pooling:", res_pool)
print("CNN without Pooling:", res_nopool)
print("CNN with Dropout:", res_dropout)
print("CNN without Dropout:", res_nodrop)

def compute_overfitting(name, res):
    train_acc, val_acc, test_acc, train_loss, val_loss, test_loss = res
    acc_gap = train_acc - val_acc
    loss_gap = val_loss - train_loss
    print(f"\n{name}-")
    print("Accuracy Gap   :", round(acc_gap,4))
    print("Loss Gap       :", round(loss_gap,4))

    return acc_gap, loss_gap
gap_pool = compute_overfitting("CNN + Pool", res_pool)
gap_nopool = compute_overfitting("CNN - Pool", res_nopool)
gap_dropout = compute_overfitting("CNN + Dropout", res_dropout)
gap_nodrop = compute_overfitting("CNN - No Dropout", res_nodrop)

# PART 3

def evaluate_cnn(model, X_data, y_data):
    correct = 0
    total_loss = 0
    for i in range(len(X_data)):
        y_hat = model.forward(X_data[i])

        loss = - (y_data[i]*np.log(y_hat+1e-8) +
                 (1-y_data[i])*np.log(1-y_hat+1e-8))
        total_loss += loss
        if (y_hat >= 0.5) == y_data[i]:
            correct += 1
    return correct/len(X_data), total_loss/len(X_data)

class SGD_CNN:
    def __init__(self, lr):
        self.lr = lr
    def step(self, model):
        model.conv.K -= self.lr * model.conv.dK
        model.conv.b -= self.lr * model.conv.db
        model.fc.W -= self.lr * model.fc.dW
        model.fc.b -= self.lr * model.fc.db

class Momentum_CNN:
    def __init__(self, lr, beta=0.9):
        self.lr = lr
        self.beta = beta
        self.v = {}
    def step(self, model):
        if not self.v:
            self.v["convK"] = np.zeros_like(model.conv.K)
            self.v["convb"] = 0
            self.v["fcW"] = np.zeros_like(model.fc.W)
            self.v["fcb"] = np.zeros_like(model.fc.b)
        self.v["convK"] = self.beta*self.v["convK"] + self.lr*model.conv.dK
        self.v["convb"] = self.beta*self.v["convb"] + self.lr*model.conv.db
        self.v["fcW"] = self.beta*self.v["fcW"] + self.lr*model.fc.dW
        self.v["fcb"] = self.beta*self.v["fcb"] + self.lr*model.fc.db
        model.conv.K -= self.v["convK"]
        model.conv.b -= self.v["convb"]
        model.fc.W -= self.v["fcW"]
        model.fc.b -= self.v["fcb"]

class Adam_CNN:
    def __init__(self, lr, beta1=0.9, beta2=0.999, eps=1e-8):
        self.lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.eps = eps
        self.m = {}
        self.v = {}
    def step(self, model):
        if not self.m:
            self.m["convK"] = np.zeros_like(model.conv.K)
            self.m["convb"] = 0
            self.m["fcW"] = np.zeros_like(model.fc.W)
            self.m["fcb"] = np.zeros_like(model.fc.b)
            self.v["convK"] = np.zeros_like(model.conv.K)
            self.v["convb"] = 0
            self.v["fcW"] = np.zeros_like(model.fc.W)
            self.v["fcb"] = np.zeros_like(model.fc.b)
        grads = {
            "convK": model.conv.dK,
            "convb": model.conv.db,
            "fcW": model.fc.dW,
            "fcb": model.fc.db
        }
        for key in grads:
            g = grads[key]
            self.m[key] = self.beta1*self.m[key] + (1-self.beta1)*g
            self.v[key] = self.beta2*self.v[key] + (1-self.beta2)*(g**2)
            update = self.lr * self.m[key] / (np.sqrt(self.v[key]) + self.eps)
            if key == "convK":
                model.conv.K -= update
            elif key == "convb":
                model.conv.b -= update
            elif key == "fcW":
                model.fc.W -= update
            elif key == "fcb":
                model.fc.b -= update

def train_with_optimizer(optimizer_class, lr=0.01, epochs=5):

    model = SimpleCNN()
    optimizer = optimizer_class(lr)

    train_loss_hist = []
    val_loss_hist   = []
    train_acc_hist  = []
    val_acc_hist    = []

    for epoch in range(epochs):

        total_loss = 0
        correct = 0

        for i in range(len(X_train)):
            X_sample = X_train[i]
            y_sample = y_train[i].reshape(1,1)

            y_hat = model.forward(X_sample)

            loss = - (y_sample*np.log(y_hat+1e-8) +
                     (1-y_sample)*np.log(1-y_hat+1e-8))

            total_loss += loss.item()

            if (y_hat >= 0.5) == y_sample:
                correct += 1

            model.backward(y_sample)
            optimizer.step(model)

        train_loss = total_loss / len(X_train)
        train_acc  = correct / len(X_train)

        val_correct = 0
        val_loss_total = 0

        for i in range(len(X_val)):
            y_hat = model.forward(X_val[i])

            loss = - (y_val[i]*np.log(y_hat+1e-8) +
                     (1-y_val[i])*np.log(1-y_hat+1e-8))

            val_loss_total += loss.item()

            if (y_hat >= 0.5) == y_val[i]:
                val_correct += 1

        val_loss = val_loss_total / len(X_val)
        val_acc  = val_correct / len(X_val)

        train_loss_hist.append(train_loss)
        val_loss_hist.append(val_loss)
        train_acc_hist.append(train_acc)
        val_acc_hist.append(val_acc)

    plt.figure()
    plt.plot(train_loss_hist, label="Train Loss")
    plt.plot(val_loss_hist, label="Val Loss")
    plt.title(f"{optimizer_class.__name__} - Loss")
    plt.legend()
    plt.show()

    plt.figure()
    plt.plot(train_acc_hist, label="Train Acc")
    plt.plot(val_acc_hist, label="Val Acc")
    plt.title(f"{optimizer_class.__name__} - Accuracy")
    plt.legend()
    plt.show()

    test_acc, test_loss = evaluate_cnn(model, X_test, y_test)
    test_acc = float(test_acc)
    test_loss = float(test_loss)
    print("Final Test Accuracy:", round(test_acc,4))
    print("Final Test Loss:", round(test_loss,4))

    return model, train_loss_hist, train_acc, val_acc, test_acc, train_loss, val_loss, test_loss

# sgd
model_sgd, loss_sgd, tr_sgd, val_sgd, te_sgd, train_loss_sgd, val_loss_sgd, test_loss_sgd = train_with_optimizer(SGD_CNN, lr=0.01)
# momentum
model_mom, loss_mom, tr_mom, val_mom, te_mom, train_loss_mom, val_loss_mom, test_loss_mom = train_with_optimizer(Momentum_CNN, lr=0.01)
# adam
model_adam, loss_adam, tr_adam, val_adam, te_adam, train_loss_adam, val_loss_adam, test_loss_adam = train_with_optimizer(Adam_CNN, lr=0.01)

def print_optimizer_values(name,
                           train_acc, val_acc, test_acc,
                           train_loss, val_loss, test_loss,
                           loss_hist):
    print(f"\n{name}")
    print("-"*60)
    print("Final Train Accuracy :", round(train_acc,4))
    print("Final Val Accuracy   :", round(val_acc,4))
    print("Final Test Accuracy  :", round(test_acc,4))
    print("Final Train Loss     :", round(train_loss,4))
    print("Final Val Loss       :", round(val_loss,4))
    print("Final Test Loss      :", round(test_loss,4))
    print("Convergence Epoch    :", int(np.argmin(loss_hist)))
    print("Loss Stability (Std) :", round(float(np.std(loss_hist)),6))
print_optimizer_values(
    "SGD",
    tr_sgd, val_sgd, te_sgd,
    train_loss_sgd, val_loss_sgd, test_loss_sgd,
    loss_sgd
)
print_optimizer_values(
    "Momentum",
    tr_mom, val_mom, te_mom,
    train_loss_mom, val_loss_mom, test_loss_mom,
    loss_mom
)
print_optimizer_values(
    "Adam",
    tr_adam, val_adam, te_adam,
    train_loss_adam, val_loss_adam, test_loss_adam,
    loss_adam
)

loss_sgd = np.array(loss_sgd).reshape(-1)
loss_mom = np.array(loss_mom).reshape(-1)
loss_adam = np.array(loss_adam).reshape(-1)

plt.plot(loss_sgd, label="SGD")
plt.plot(loss_mom, label="Momentum")
plt.plot(loss_adam, label="Adam")
plt.title("Optimizer Convergence")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

# MASTER RESULT TABLE
print("MASTER RESULT TABLE")
master_table = []
for r in results:
    depth_name = r[0]
    activation = r[1]
    optimizer  = r[2]
    train_acc  = r[3]
    val_acc    = r[4]
    test_acc   = r[5]
    if depth_name == "2-layer":
        temp_model = DenseNetwork([2,8,1], activation=activation)
    elif depth_name == "5-layer":
        temp_model = DenseNetwork([2,8,8,8,8,1], activation=activation)
    else:
        temp_model = DenseNetwork([2]+[8]*9+[1], activation=activation)
    dense_params = 0
    for l in range(1, temp_model.L+1):
        dense_params += temp_model.W[l].size
        dense_params += temp_model.b[l].size
    master_table.append([
        "Dense",
        depth_name,
        activation,
        optimizer,
        dense_params,
        round(train_acc,4),
        round(val_acc,4),
        round(test_acc,4)
    ])
dense_image_params = model_dense.W1.size + model_dense.b1.size + \
                     model_dense.W2.size + model_dense.b2.size
master_table.append([
    "Dense(Image)",
    "-",
    "ReLU",
    "SGD",
    dense_image_params,
    round(accuracy(y_train,train_pred),4),
    round(accuracy(y_val,val_pred),4),
    round(accuracy(y_test,test_pred),4)
])
cnn_params = cnn.conv.K.size + 1 + cnn.fc.W.size + cnn.fc.b.size
master_table.append([
    "CNN+Pool",
    "-",
    "ReLU",
    "SGD",
    cnn_params,
    round(res_pool[0],4),
    round(res_pool[1],4),
    round(res_pool[2],4)
])
master_table.append([
    "CNN-NoPool",
    "-",
    "ReLU",
    "SGD",
    cnn_params,
    round(res_nopool[0],4),
    round(res_nopool[1],4),
    round(res_nopool[2],4)
])
master_table.append([
    "CNN+Dropout",
    "-",
    "ReLU",
    "SGD",
    cnn_params,
    round(res_dropout[0],4),
    round(res_dropout[1],4),
    round(res_dropout[2],4)
])
master_table.append([
    "CNN-NoDrop",
    "-",
    "ReLU",
    "SGD",
    cnn_params,
    round(res_nodrop[0],4),
    round(res_nodrop[1],4),
    round(res_nodrop[2],4)
])
master_table.append([
    "CNN",
    "-",
    "ReLU",
    "SGD",
    cnn_params,
    round(tr_sgd,4),
    round(val_sgd,4),
    round(te_sgd,4)
])
master_table.append([
    "CNN",
    "-",
    "ReLU",
    "Momentum",
    cnn_params,
    round(tr_mom,4),
    round(val_mom,4),
    round(te_mom,4)
])
master_table.append([
    "CNN",
    "-",
    "ReLU",
    "Adam",
    cnn_params,
    round(tr_adam,4),
    round(val_adam,4),
    round(te_adam,4)
])
header = "{:<15} {:<10} {:<10} {:<12} {:<12} {:<10} {:<10} {:<10}"
print(header.format("Model","Depth","Activation","Optimizer",
                    "Parameters","TrainAcc","ValAcc","TestAcc"))
print("-"*120)
for row in master_table:
    print(header.format(*row))
print("Total Models Reported:", len(master_table))
